services:
  app:
    container_name: cloud-file-storage
    image: 230355214351.dkr.ecr.eu-central-1.amazonaws.com/myapp/ecr:test-dev
    ports:
      - "80:5000"
    restart: unless-stopped
    env_file:
      - .env
